### ISSUE TITLE
Calculate average income by region in Korea

### ISSUE THREAD

**Issue by chanwoolkim** [chanwoolkim/korean_housing#1]
We want to calculate the average income for the working population in Korea at the City-Gu level. Because we do not have access to the credit bureau data yet, we will use this to substitute for individual credit scores. We will do the following:

- [x] Download raw data files and store them in Dropbox
- [x] Calculated weighted average of household labour income by City-Gu
- [x] Find if there are any additional relevant statistics to extract in terms of income/wealth, and calculate
- [x] If there are any changes in City-Gu, comment here and we will decide which timeframe to use

**Comment by minjikang0322** [comment]
Because each city code has a different number of subcodes, it is difficult to use 'for' to calculate average income by Gu.

**Comment by minjikang0322** [comment]
USE tidyverse-dplyr package.

**Comment by minjikang0322** [comment]
Because of my inexperience with R, I don't have enough time to finish this task until 9/4. I promise to finish this task by 9/8 and I am going to devote a lot of time to the Korean-housing project during 추석. Please let me know if there is another task to prepare for the project. Also, if you need the result of average income by region immediately, please refer to the calculated excel file and raw data on dropbox. TT

**Comment by chanwoolkim** [comment]
@minjikang0322 I recommend using the `group_by` and `summarise` functions in the `dplyr` package (piping in R is an amazing tool). You want to make sure you set `na.rm=TRUE`. You also want to review the [ck_lab_docs](https://docs.google.com/document/d/1fTIFcyhsXjLPqfyTtSoaD13kRL-DCKKNZTAL6pZ9xS0/edit?usp=sharing) again to format these comments well (generally you should try to include/format 'problems raised in the task,' 'how you plan to solve the problems/how the problems were solved,' 'request for comments/review,' and 'your comments' if any).

**Comment by minjikang0322** [comment]
I am studying R by referring to the book. I'm especially focused on the data types.

**Comment by minjikang0322** [comment]
I finished calculating weighted average of household labour income by City-Gu with python. I uploaded the code in Dropbox. @chanwoolkim

**Comment by chanwoolkim** [comment]
@minjikang0322 
Please review the [ck_lab_docs](https://docs.google.com/document/d/1fTIFcyhsXjLPqfyTtSoaD13kRL-DCKKNZTAL6pZ9xS0/edit?usp=sharing) again, especially the section on Git issues. You want to create a branch based on your issue number and also leave the issue number in your commit messages. That way we can track which code refers to which issue.

**Comment by minjikang0322** [comment]
@chanwoolkim I changed the branch's name to 'issue1_weighted average labor income'.

**Comment by minjikang0322** [comment]
@chanwoolkim I found additional relevant statistics in 한국노동패널. I think 'Financial asset' is relevant to credit bureau data. But I am not sure if financial asset data is more appropriate than average income data.

**Comment by minjikang0322** [comment]
We used 2011 total income data because it was used in 'Jing, Park, and Zhang'. However, there were changes in City Gu. 세종시 was established in July 2012 and 청주 청원구 & 청주 서원구 were established in July 2014.

**Comment by minjikang0322** [comment]
![image](https://user-images.githubusercontent.com/97087669/192595446-a44c68ee-2b6a-4493-af12-e4639e0bc697.png)
Referring to the above, I think it is appropriate to use 2011 data even if there are changes in the city-gu.

**Comment by chanwoolkim** [comment]
@minjikang0322 I agree with just sticking with the 2011 data. We can change things if we decide to focus on some other period later.
